<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../../SharedImports/CsProj.Props/AllImportsForRealCode-Nullable.props" />

  <!-- As of 2026-06-28 2dm this should not be exported ATM -->
  <!--<Import Project="../../SharedImports/CsProj.Props/CreateXDocsOnRelease.props" />-->

  <PropertyGroup>
    <AssemblyName>ToSic.Sxc.Code.HotBuild</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ToSic.Sxc.Core\ToSic.Sxc.Core.csproj" />
  </ItemGroup>

</Project>
