using ToSic.Sxc.Code.Generate.Sys;

namespace ToSic.Sxc.WebApi.Tests.CodeGeneration;

internal sealed class TestAutoGenerateFileGenerator : IFileGenerator
{
    internal const string GeneratorName = "TestAutoGenerateGenerator";
    internal const string FileName = "AutoGenerated.txt";

    private readonly List<IFileGeneratorSpecs> _receivedSpecs = [];

    public IReadOnlyList<IFileGeneratorSpecs> ReceivedSpecs => _receivedSpecs;
    public string NameId => Name;
    public string Name => GeneratorName;
    public string Version => "1.0.0";
    public string Description => "Test auto-generate file generator";
    public string DescriptionHtml => Description;
    public string OutputLanguage => "Text";
    public string OutputType => "Test";

    public IGeneratedFileSet[] Generate(IFileGeneratorSpecs specs)
    {
        _receivedSpecs.Add(specs);

        return
        [
            new GeneratedFileSet
            {
                Name = "Test auto-generate output",
                Description = "Test auto-generate output",
                Generator = Name,
                Path = GenerateConstants.PathToAppCode,
                Files =
                [
                    new GeneratedFile
                    {
                        FileName = FileName,
                        Path = "Data",
                        Body = "auto-generated"
                    }
                ]
            }
        ];
    }
}

