using ToSic.Sxc.Code.Internal.HotBuild;

namespace ToSic.Sxc.Code.Internal.Generate;

public class CodeGenSpecs
{
    public string AppName { get; set; } = "App";

    /// <summary>
    /// Namespace for the data classes
    /// </summary>
    public string DataNamespace { get; set; } = ThisAppLoader.ThisAppBase + ".Data";

    /// <summary>
    /// This is added to the end of the class name to indicate that it was auto-generated.
    /// It's quite verbose, to ensure that it's unlikely to clash with a real class name.
    /// </summary>
    public string DataClassGeneratedSuffix { get; set; } = "AutoGenerated";

    /// <summary>
    /// Default class to inherit from - ATM Item16 only
    /// </summary>
    public string DataInherits { get; set; } = "Custom.Data.Item16";

    /// <summary>
    /// The edition of the generated code
    /// </summary>
    public string Edition { get; set; } = "";

    /// <summary>
    /// This is added to the end of a file name to indicate that it was auto-generated.
    /// It's shorter for practical reasons, and should start with a dot and a letter > "c"
    /// so that in the list of files it will be after the ".cs" file which may be created.
    /// </summary>
    public string FileGeneratedSuffix { get; set; } = ".Generated";

    /// <summary>
    /// Tab size for the generated code
    /// </summary>
    public int TabSize { get; set; } = 2;

    /// <summary>
    /// Tabs in front of namespace code
    /// </summary>
    public int TabsNamespace { get; set; } = 0;

    /// <summary>
    /// Tabs in front of class code
    /// </summary>
    public int TabsClass { get; set; } = 1;

    /// <summary>
    /// Tabs in front of property code
    /// </summary>
    public int TabsProperty { get; set; } = 2;

}