//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ToSic.SexyContent", "FK_ToSIC_SexyContent_ContentGroupItems_ToSIC_SexyContent_Templates", "ToSIC_SexyContent_Templates", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ToSic.SexyContent.Template), "ToSIC_SexyContent_ContentGroupItems", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ToSic.SexyContent.ContentGroupItem), true)]

#endregion

namespace ToSic.SexyContent
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SexyContentContextBase : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SexyContentContextBase object using the connection string found in the 'SexyContentContextBase' section of the application configuration file.
        /// </summary>
        public SexyContentContextBase() : base("name=SexyContentContextBase", "SexyContentContextBase")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SexyContentContextBase object.
        /// </summary>
        public SexyContentContextBase(string connectionString) : base(connectionString, "SexyContentContextBase")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SexyContentContextBase object.
        /// </summary>
        public SexyContentContextBase(EntityConnection connection) : base(connection, "SexyContentContextBase")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ContentGroupItem> ContentGroupItems
        {
            get
            {
                if ((_ContentGroupItems == null))
                {
                    _ContentGroupItems = base.CreateObjectSet<ContentGroupItem>("ContentGroupItems");
                }
                return _ContentGroupItems;
            }
        }
        private ObjectSet<ContentGroupItem> _ContentGroupItems;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Template> Templates
        {
            get
            {
                if ((_Templates == null))
                {
                    _Templates = base.CreateObjectSet<Template>("Templates");
                }
                return _Templates;
            }
        }
        private ObjectSet<Template> _Templates;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ContentGroupItems EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToContentGroupItems(ContentGroupItem contentGroupItem)
        {
            base.AddObject("ContentGroupItems", contentGroupItem);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Templates EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTemplates(Template template)
        {
            base.AddObject("Templates", template);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ToSic.SexyContent", Name="ContentGroupItem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ContentGroupItem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ContentGroupItem object.
        /// </summary>
        /// <param name="contentGroupItemID">Initial value of the ContentGroupItemID property.</param>
        /// <param name="contentGroupID">Initial value of the ContentGroupID property.</param>
        /// <param name="sortOrder">Initial value of the SortOrder property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        /// <param name="sysCreated">Initial value of the SysCreated property.</param>
        /// <param name="sysCreatedBy">Initial value of the SysCreatedBy property.</param>
        /// <param name="sysModified">Initial value of the SysModified property.</param>
        /// <param name="sysModifiedBy">Initial value of the SysModifiedBy property.</param>
        public static ContentGroupItem CreateContentGroupItem(global::System.Int32 contentGroupItemID, global::System.Int32 contentGroupID, global::System.Int32 sortOrder, global::System.String type, global::System.DateTime sysCreated, global::System.Int32 sysCreatedBy, global::System.DateTime sysModified, global::System.Int32 sysModifiedBy)
        {
            ContentGroupItem contentGroupItem = new ContentGroupItem();
            contentGroupItem.ContentGroupItemID = contentGroupItemID;
            contentGroupItem.ContentGroupID = contentGroupID;
            contentGroupItem.SortOrder = sortOrder;
            contentGroupItem.Type = type;
            contentGroupItem.SysCreated = sysCreated;
            contentGroupItem.SysCreatedBy = sysCreatedBy;
            contentGroupItem.SysModified = sysModified;
            contentGroupItem.SysModifiedBy = sysModifiedBy;
            return contentGroupItem;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ContentGroupItemID
        {
            get
            {
                return _ContentGroupItemID;
            }
            set
            {
                if (_ContentGroupItemID != value)
                {
                    OnContentGroupItemIDChanging(value);
                    ReportPropertyChanging("ContentGroupItemID");
                    _ContentGroupItemID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ContentGroupItemID");
                    OnContentGroupItemIDChanged();
                }
            }
        }
        private global::System.Int32 _ContentGroupItemID;
        partial void OnContentGroupItemIDChanging(global::System.Int32 value);
        partial void OnContentGroupItemIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ContentGroupID
        {
            get
            {
                return _ContentGroupID;
            }
            set
            {
                OnContentGroupIDChanging(value);
                ReportPropertyChanging("ContentGroupID");
                _ContentGroupID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ContentGroupID");
                OnContentGroupIDChanged();
            }
        }
        private global::System.Int32 _ContentGroupID;
        partial void OnContentGroupIDChanging(global::System.Int32 value);
        partial void OnContentGroupIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> EntityID
        {
            get
            {
                return _EntityID;
            }
            set
            {
                OnEntityIDChanging(value);
                ReportPropertyChanging("EntityID");
                _EntityID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EntityID");
                OnEntityIDChanged();
            }
        }
        private Nullable<global::System.Int32> _EntityID;
        partial void OnEntityIDChanging(Nullable<global::System.Int32> value);
        partial void OnEntityIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TemplateID
        {
            get
            {
                return _TemplateID;
            }
            set
            {
                OnTemplateIDChanging(value);
                ReportPropertyChanging("TemplateID");
                _TemplateID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TemplateID");
                OnTemplateIDChanged();
            }
        }
        private Nullable<global::System.Int32> _TemplateID;
        partial void OnTemplateIDChanging(Nullable<global::System.Int32> value);
        partial void OnTemplateIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SortOrder
        {
            get
            {
                return _SortOrder;
            }
            set
            {
                OnSortOrderChanging(value);
                ReportPropertyChanging("SortOrder");
                _SortOrder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SortOrder");
                OnSortOrderChanged();
            }
        }
        private global::System.Int32 _SortOrder;
        partial void OnSortOrderChanging(global::System.Int32 value);
        partial void OnSortOrderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime SysCreated
        {
            get
            {
                return _SysCreated;
            }
            set
            {
                OnSysCreatedChanging(value);
                ReportPropertyChanging("SysCreated");
                _SysCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SysCreated");
                OnSysCreatedChanged();
            }
        }
        private global::System.DateTime _SysCreated;
        partial void OnSysCreatedChanging(global::System.DateTime value);
        partial void OnSysCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SysCreatedBy
        {
            get
            {
                return _SysCreatedBy;
            }
            set
            {
                OnSysCreatedByChanging(value);
                ReportPropertyChanging("SysCreatedBy");
                _SysCreatedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SysCreatedBy");
                OnSysCreatedByChanged();
            }
        }
        private global::System.Int32 _SysCreatedBy;
        partial void OnSysCreatedByChanging(global::System.Int32 value);
        partial void OnSysCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime SysModified
        {
            get
            {
                return _SysModified;
            }
            set
            {
                OnSysModifiedChanging(value);
                ReportPropertyChanging("SysModified");
                _SysModified = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SysModified");
                OnSysModifiedChanged();
            }
        }
        private global::System.DateTime _SysModified;
        partial void OnSysModifiedChanging(global::System.DateTime value);
        partial void OnSysModifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SysModifiedBy
        {
            get
            {
                return _SysModifiedBy;
            }
            set
            {
                OnSysModifiedByChanging(value);
                ReportPropertyChanging("SysModifiedBy");
                _SysModifiedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SysModifiedBy");
                OnSysModifiedByChanged();
            }
        }
        private global::System.Int32 _SysModifiedBy;
        partial void OnSysModifiedByChanging(global::System.Int32 value);
        partial void OnSysModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> SysDeleted
        {
            get
            {
                return _SysDeleted;
            }
            set
            {
                OnSysDeletedChanging(value);
                ReportPropertyChanging("SysDeleted");
                _SysDeleted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SysDeleted");
                OnSysDeletedChanged();
            }
        }
        private Nullable<global::System.DateTime> _SysDeleted;
        partial void OnSysDeletedChanging(Nullable<global::System.DateTime> value);
        partial void OnSysDeletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SysDeletedBy
        {
            get
            {
                return _SysDeletedBy;
            }
            set
            {
                OnSysDeletedByChanging(value);
                ReportPropertyChanging("SysDeletedBy");
                _SysDeletedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SysDeletedBy");
                OnSysDeletedByChanged();
            }
        }
        private Nullable<global::System.Int32> _SysDeletedBy;
        partial void OnSysDeletedByChanging(Nullable<global::System.Int32> value);
        partial void OnSysDeletedByChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ToSic.SexyContent", "FK_ToSIC_SexyContent_ContentGroupItems_ToSIC_SexyContent_Templates", "ToSIC_SexyContent_Templates")]
        public Template ToSIC_SexyContent_Templates
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Template>("ToSic.SexyContent.FK_ToSIC_SexyContent_ContentGroupItems_ToSIC_SexyContent_Templates", "ToSIC_SexyContent_Templates").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Template>("ToSic.SexyContent.FK_ToSIC_SexyContent_ContentGroupItems_ToSIC_SexyContent_Templates", "ToSIC_SexyContent_Templates").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Template> ToSIC_SexyContent_TemplatesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Template>("ToSic.SexyContent.FK_ToSIC_SexyContent_ContentGroupItems_ToSIC_SexyContent_Templates", "ToSIC_SexyContent_Templates");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Template>("ToSic.SexyContent.FK_ToSIC_SexyContent_ContentGroupItems_ToSIC_SexyContent_Templates", "ToSIC_SexyContent_Templates", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ToSic.SexyContent", Name="Template")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Template : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Template object.
        /// </summary>
        /// <param name="templateID">Initial value of the TemplateID property.</param>
        /// <param name="portalID">Initial value of the PortalID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="path">Initial value of the Path property.</param>
        /// <param name="script">Initial value of the Script property.</param>
        /// <param name="isFile">Initial value of the IsFile property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        /// <param name="isHidden">Initial value of the IsHidden property.</param>
        /// <param name="location">Initial value of the Location property.</param>
        /// <param name="useForList">Initial value of the UseForList property.</param>
        /// <param name="useForItem">Initial value of the UseForItem property.</param>
        /// <param name="sysCreated">Initial value of the SysCreated property.</param>
        /// <param name="sysCreatedBy">Initial value of the SysCreatedBy property.</param>
        /// <param name="sysModified">Initial value of the SysModified property.</param>
        /// <param name="sysModifiedBy">Initial value of the SysModifiedBy property.</param>
        /// <param name="appID">Initial value of the AppID property.</param>
        /// <param name="publishData">Initial value of the PublishData property.</param>
        /// <param name="streamsToPublish">Initial value of the StreamsToPublish property.</param>
        public static Template CreateTemplate(global::System.Int32 templateID, global::System.Int32 portalID, global::System.String name, global::System.String path, global::System.String script, global::System.Boolean isFile, global::System.String type, global::System.Boolean isHidden, global::System.String location, global::System.Boolean useForList, global::System.Boolean useForItem, global::System.DateTime sysCreated, global::System.Int32 sysCreatedBy, global::System.DateTime sysModified, global::System.Int32 sysModifiedBy, global::System.Int32 appID, global::System.Boolean publishData, global::System.String streamsToPublish)
        {
            Template template = new Template();
            template.TemplateID = templateID;
            template.PortalID = portalID;
            template.Name = name;
            template.Path = path;
            template.Script = script;
            template.IsFile = isFile;
            template.Type = type;
            template.IsHidden = isHidden;
            template.Location = location;
            template.UseForList = useForList;
            template.UseForItem = useForItem;
            template.SysCreated = sysCreated;
            template.SysCreatedBy = sysCreatedBy;
            template.SysModified = sysModified;
            template.SysModifiedBy = sysModifiedBy;
            template.AppID = appID;
            template.PublishData = publishData;
            template.StreamsToPublish = streamsToPublish;
            return template;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TemplateID
        {
            get
            {
                return _TemplateID;
            }
            set
            {
                if (_TemplateID != value)
                {
                    OnTemplateIDChanging(value);
                    ReportPropertyChanging("TemplateID");
                    _TemplateID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TemplateID");
                    OnTemplateIDChanged();
                }
            }
        }
        private global::System.Int32 _TemplateID;
        partial void OnTemplateIDChanging(global::System.Int32 value);
        partial void OnTemplateIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PortalID
        {
            get
            {
                return _PortalID;
            }
            set
            {
                OnPortalIDChanging(value);
                ReportPropertyChanging("PortalID");
                _PortalID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PortalID");
                OnPortalIDChanged();
            }
        }
        private global::System.Int32 _PortalID;
        partial void OnPortalIDChanging(global::System.Int32 value);
        partial void OnPortalIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Path
        {
            get
            {
                return _Path;
            }
            set
            {
                OnPathChanging(value);
                ReportPropertyChanging("Path");
                _Path = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Path");
                OnPathChanged();
            }
        }
        private global::System.String _Path;
        partial void OnPathChanging(global::System.String value);
        partial void OnPathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AttributeSetID
        {
            get
            {
                return _AttributeSetID;
            }
            set
            {
                OnAttributeSetIDChanging(value);
                ReportPropertyChanging("AttributeSetID");
                _AttributeSetID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AttributeSetID");
                OnAttributeSetIDChanged();
            }
        }
        private Nullable<global::System.Int32> _AttributeSetID;
        partial void OnAttributeSetIDChanging(Nullable<global::System.Int32> value);
        partial void OnAttributeSetIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DemoEntityID
        {
            get
            {
                return _DemoEntityID;
            }
            set
            {
                OnDemoEntityIDChanging(value);
                ReportPropertyChanging("DemoEntityID");
                _DemoEntityID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DemoEntityID");
                OnDemoEntityIDChanged();
            }
        }
        private Nullable<global::System.Int32> _DemoEntityID;
        partial void OnDemoEntityIDChanging(Nullable<global::System.Int32> value);
        partial void OnDemoEntityIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Script
        {
            get
            {
                return _Script;
            }
            set
            {
                OnScriptChanging(value);
                ReportPropertyChanging("Script");
                _Script = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Script");
                OnScriptChanged();
            }
        }
        private global::System.String _Script;
        partial void OnScriptChanging(global::System.String value);
        partial void OnScriptChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsFile
        {
            get
            {
                return _IsFile;
            }
            set
            {
                OnIsFileChanging(value);
                ReportPropertyChanging("IsFile");
                _IsFile = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsFile");
                OnIsFileChanged();
            }
        }
        private global::System.Boolean _IsFile;
        partial void OnIsFileChanging(global::System.Boolean value);
        partial void OnIsFileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsHidden
        {
            get
            {
                return _IsHidden;
            }
            set
            {
                OnIsHiddenChanging(value);
                ReportPropertyChanging("IsHidden");
                _IsHidden = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsHidden");
                OnIsHiddenChanged();
            }
        }
        private global::System.Boolean _IsHidden;
        partial void OnIsHiddenChanging(global::System.Boolean value);
        partial void OnIsHiddenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Location
        {
            get
            {
                return _Location;
            }
            set
            {
                OnLocationChanging(value);
                ReportPropertyChanging("Location");
                _Location = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Location");
                OnLocationChanged();
            }
        }
        private global::System.String _Location;
        partial void OnLocationChanging(global::System.String value);
        partial void OnLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean UseForList
        {
            get
            {
                return _UseForList;
            }
            set
            {
                OnUseForListChanging(value);
                ReportPropertyChanging("UseForList");
                _UseForList = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UseForList");
                OnUseForListChanged();
            }
        }
        private global::System.Boolean _UseForList;
        partial void OnUseForListChanging(global::System.Boolean value);
        partial void OnUseForListChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean UseForItem
        {
            get
            {
                return _UseForItem;
            }
            set
            {
                OnUseForItemChanging(value);
                ReportPropertyChanging("UseForItem");
                _UseForItem = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UseForItem");
                OnUseForItemChanged();
            }
        }
        private global::System.Boolean _UseForItem;
        partial void OnUseForItemChanging(global::System.Boolean value);
        partial void OnUseForItemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime SysCreated
        {
            get
            {
                return _SysCreated;
            }
            set
            {
                OnSysCreatedChanging(value);
                ReportPropertyChanging("SysCreated");
                _SysCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SysCreated");
                OnSysCreatedChanged();
            }
        }
        private global::System.DateTime _SysCreated;
        partial void OnSysCreatedChanging(global::System.DateTime value);
        partial void OnSysCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SysCreatedBy
        {
            get
            {
                return _SysCreatedBy;
            }
            set
            {
                OnSysCreatedByChanging(value);
                ReportPropertyChanging("SysCreatedBy");
                _SysCreatedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SysCreatedBy");
                OnSysCreatedByChanged();
            }
        }
        private global::System.Int32 _SysCreatedBy;
        partial void OnSysCreatedByChanging(global::System.Int32 value);
        partial void OnSysCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime SysModified
        {
            get
            {
                return _SysModified;
            }
            set
            {
                OnSysModifiedChanging(value);
                ReportPropertyChanging("SysModified");
                _SysModified = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SysModified");
                OnSysModifiedChanged();
            }
        }
        private global::System.DateTime _SysModified;
        partial void OnSysModifiedChanging(global::System.DateTime value);
        partial void OnSysModifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SysModifiedBy
        {
            get
            {
                return _SysModifiedBy;
            }
            set
            {
                OnSysModifiedByChanging(value);
                ReportPropertyChanging("SysModifiedBy");
                _SysModifiedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SysModifiedBy");
                OnSysModifiedByChanged();
            }
        }
        private global::System.Int32 _SysModifiedBy;
        partial void OnSysModifiedByChanging(global::System.Int32 value);
        partial void OnSysModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> SysDeleted
        {
            get
            {
                return _SysDeleted;
            }
            set
            {
                OnSysDeletedChanging(value);
                ReportPropertyChanging("SysDeleted");
                _SysDeleted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SysDeleted");
                OnSysDeletedChanged();
            }
        }
        private Nullable<global::System.DateTime> _SysDeleted;
        partial void OnSysDeletedChanging(Nullable<global::System.DateTime> value);
        partial void OnSysDeletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SysDeletedBy
        {
            get
            {
                return _SysDeletedBy;
            }
            set
            {
                OnSysDeletedByChanging(value);
                ReportPropertyChanging("SysDeletedBy");
                _SysDeletedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SysDeletedBy");
                OnSysDeletedByChanged();
            }
        }
        private Nullable<global::System.Int32> _SysDeletedBy;
        partial void OnSysDeletedByChanging(Nullable<global::System.Int32> value);
        partial void OnSysDeletedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AppID
        {
            get
            {
                return _AppID;
            }
            set
            {
                OnAppIDChanging(value);
                ReportPropertyChanging("AppID");
                _AppID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AppID");
                OnAppIDChanged();
            }
        }
        private global::System.Int32 _AppID;
        partial void OnAppIDChanging(global::System.Int32 value);
        partial void OnAppIDChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean PublishData
        {
            get
            {
                return _PublishData;
            }
            set
            {
                OnPublishDataChanging(value);
                ReportPropertyChanging("PublishData");
                _PublishData = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PublishData");
                OnPublishDataChanged();
            }
        }
        private global::System.Boolean _PublishData;
        partial void OnPublishDataChanging(global::System.Boolean value);
        partial void OnPublishDataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StreamsToPublish
        {
            get
            {
                return _StreamsToPublish;
            }
            set
            {
                OnStreamsToPublishChanging(value);
                ReportPropertyChanging("StreamsToPublish");
                _StreamsToPublish = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("StreamsToPublish");
                OnStreamsToPublishChanged();
            }
        }
        private global::System.String _StreamsToPublish;
        partial void OnStreamsToPublishChanging(global::System.String value);
        partial void OnStreamsToPublishChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PipelineEntityID
        {
            get
            {
                return _PipelineEntityID;
            }
            set
            {
                OnPipelineEntityIDChanging(value);
                ReportPropertyChanging("PipelineEntityID");
                _PipelineEntityID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PipelineEntityID");
                OnPipelineEntityIDChanged();
            }
        }
        private Nullable<global::System.Int32> _PipelineEntityID;
        partial void OnPipelineEntityIDChanging(Nullable<global::System.Int32> value);
        partial void OnPipelineEntityIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ViewNameInUrl
        {
            get
            {
                return _ViewNameInUrl;
            }
            set
            {
                OnViewNameInUrlChanging(value);
                ReportPropertyChanging("ViewNameInUrl");
                _ViewNameInUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ViewNameInUrl");
                OnViewNameInUrlChanged();
            }
        }
        private global::System.String _ViewNameInUrl;
        partial void OnViewNameInUrlChanging(global::System.String value);
        partial void OnViewNameInUrlChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ToSic.SexyContent", "FK_ToSIC_SexyContent_ContentGroupItems_ToSIC_SexyContent_Templates", "ToSIC_SexyContent_ContentGroupItems")]
        public EntityCollection<ContentGroupItem> ToSIC_SexyContent_ContentGroupItems
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ContentGroupItem>("ToSic.SexyContent.FK_ToSIC_SexyContent_ContentGroupItems_ToSIC_SexyContent_Templates", "ToSIC_SexyContent_ContentGroupItems");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ContentGroupItem>("ToSic.SexyContent.FK_ToSIC_SexyContent_ContentGroupItems_ToSIC_SexyContent_Templates", "ToSIC_SexyContent_ContentGroupItems", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
