using ToSic.Eav.Apps;
using ToSic.Eav.Sys;

namespace ToSic.Sxc.Code.Generate.Sys;

[PrivateApi]
[ShowApiWhenReleased(ShowApiMode.Never)]
internal record CSharpCodeSpecs: FileGeneratorSpecs
{
    private const string ItemAccessorDefault = "_item"; // TODO: nameof(CustomItem._item);
    private const string DefAutoGenNamespace = "AutoGenerated";

    public string AppName { get; init; } = "App";

    internal IAppReadContentTypes AppContentTypes { get; init; } = null!; // not sure where this is set, nullability should be improved

    public List<IContentType> ExportedContentContentTypes { get; init; } = null!; // not sure where this is set, nullability should be improved

    /// <summary>
    /// Namespace for the data classes
    /// </summary>
    public string DataNamespace { get; init; } = $"{FolderConstants.AppCodeFolder}.Data";

    public string NamespaceAutoGen { get; init; } = DefAutoGenNamespace;

    /// <summary>
    /// Namespace for the data classes
    /// </summary>
    public string DataNamespaceGenerated => $"{DataNamespace}.{NamespaceAutoGen}";

    /// <summary>
    /// This is added to the end of the class name to indicate that it was auto-generated.
    /// It's quite verbose, to ensure that it's unlikely to clash with a real class name.
    /// </summary>
    public string DataClassGeneratedSuffix { get; init; } = "";

    public string DataClassGeneratedPrefix { get; init; } = "ZAutoGen";

    /// <summary>
    /// Default class to inherit from - ATM CustomItem only
    /// </summary>
    public string DataInherits { get; init; } = "Custom.Data.CustomItem";

    public string ItemAccessor { get; init; } = ItemAccessorDefault;


    /// <summary>
    /// This is added to the end of a file name to indicate that it was auto-generated.
    /// It's shorter for practical reasons, and should start with a dot and a letter > "c"
    /// so that in the list of files it will be after the ".cs" file which may be created.
    /// </summary>
    public string FileGeneratedSuffix { get; init; } = ".Generated";

    /// <summary>
    /// Tab size for the generated code
    /// </summary>
    public int TabSize { get; init; } = 2;

    /// <summary>
    /// Tabs in front of namespace code
    /// </summary>
    public int TabsNamespace { get; init; } = 0;

    /// <summary>
    /// Tabs in front of class code
    /// </summary>
    public int TabsClass { get; init; } = 1;

    /// <summary>
    /// Tabs in front of property code
    /// </summary>
    public int TabsProperty { get; init; } = 2;
}